### ISSUE TITLE
Simply doesn't work and breaks the volumio installation

### ISSUE THREAD

**Issue by webbes** [Saiyato/volumio-snapcast-plugin#6] opened 2017-06-14 09:00 UTC
Plugin never switches to active, doesn't work and uninstall does not revert the changes that were made to config files, so it leaves your installation broken. I am excited about the initiative though.

Volumio version 2.185

**Comment by Saiyato** [comment] 2017-06-14 09:37
You are correct sir,  it is nowhere near a real release though ;)

Will try to patch things in the uninstall script.

**Comment by Saiyato** [comment] 2017-06-14 09:47
Created issue #7  for the active sign

Will commit in a few seconds with more uninstall options, can't really determine the asound.conf though. This is for more advanced users, use with care!

As for the plugin not working, please elaborate, because "doesn't work" does not help me much. What did you try? Spotify? Qobuz? MPD? What hardware and configuration did you use? If you can provide me with a case I can investigate what might have gone wrong. :)

**Comment by Saiyato** [comment] 2017-06-14 11:04
> As for the plugin not working, please elaborate, because "doesn't work" does not help me much. What did you try? Spotify? Qobuz? MPD? What hardware and configuration did you use? If you can provide me with a case I can investigate what might have gone wrong. :)

**Comment by webbes** [comment] 2017-06-14 13:04
I've installed the plugin on two RaspberryPI 3 devices that have a PiFi Dac Plus HAT (compatible with HiFiBerry). Installation seems to be fine. However, activating and configuring the plugin does not seems to have a lot of effect. One device runs only the client (called client from now on) and the other device runs both the server and the client (called host from now on). However, disabling the server on the client, does not have any impact as it appears running after reboot. 

What does work is naming the host. Changing the name works and the client on both devices is able to see the host by name as it is available in the drop down list.

I did hit save on every safe button on both client and host machine to ensure that the configuration changes were applied to all the configuration files. Then I safely restarted both devices. Host first, client second.

After reboot I can playback any music from Spotify, NAS or web radio, locally on the host machine, but the client machine does not output anything at all.

Further I noticed that the plugin status on both the client machine and host machine is still "inactive" no matter the changes.

Uninstalling the plugin does not revert the configuration changes so you end up with two devices that do not output anything at all.

After reimaging and configuration the two devices work standalone as before so nothing is permanently bricked.

If you need more info, please let me know. If you want me to test the plugin again, just let me know. I'll make a copy of the SD and simply retry. I don't mind to be your tester for this hardware setup. I really like your effort and your super fast reply is encouraging.

**Comment by Saiyato** [comment] 2017-06-14 14:39
Check, this clarifies for me.

Issue #7 is created for the plugin not showing as active. This needs some investigation.

You say you can play music on the host, so the localhost setting works, right? This is because I translate the localhost to 127.0.0.1. If the host doesn't output sound please let me know.

Does the client play if you fill in the IP-address using a 'custom host'? I think NAT is not working correctly, I will investigate further.

Uninstalling should now at least enable ALSA output again, but you should use the latest upload (of today). But since I'm not at home I have not tested this. Removing the asound.conf seemed a bit too much, since I can't make sure noone else has written anything to/in it. Maybe if someone can make a nice sed command I can implement that. The asound should however, since I don't change defaults, not be a problem.

**Comment by webbes** [comment] 2017-06-14 21:31
Using the latest upload: With the client pointing to the statically assigned ip of the server it works for both internet radio and nas playback. Which is a great leap forward. With Spotify doesn't work.

The plugin still shows as inactive (noticed you filed a bug) and even though I did disable snap server on the client device, it appears to be enabled when reloading the settings page.

Keep up the good work and let me know if I can test again. If you get it to work with Spotify you are my hero.

If you come with a new version, I'll first test the Uninstall. Right now I prefer to keep it working as it is...

**Comment by Saiyato** [comment] 2017-06-15 19:53
Just checked in a new version; this fixes the plugin not showing as active and the volumio hosts NAT problem.

Spotify support is near, but not ready yet. Which Spotify implementation are you using?

**Comment by webbes** [comment] 2017-06-16 09:19
Great thx. Will test this weekend. I'm using the default available Spotify plugin.

**Comment by webbes** [comment] 2017-06-17 09:03
First deactivated and then uninstalled the previous version of the plugin. This unfortunately left the Volumio installation broken. Could not play music, and an attempt to connect to my Music Library killed the device. Lost connection to BOTH devices. Reboot brought the devices back online, but did not solve the problem. An attempt to connect to the Music Library again resulted in a complete loss of connection.

After a clean install I've uploaded the latest version of the plugin. Indeed, the plugin does now show active and works for both NAS and WebRadio. The settings however are not bound to the current configuration. So if I stop de server on the client device, and then reload the settings page, it looks like the server is enabled, which is confusing.

Hope this helps,
Wes

**Comment by Saiyato** [comment] 2017-06-20 12:16
> First deactivated and then uninstalled the previous version of the plugin. This unfortunately left the Volumio installation broken. Could not play music, and an attempt to connect to my Music Library killed the device. Lost connection to BOTH devices. Reboot brought the devices back online, but did not solve the problem. An attempt to connect to the Music Library again resulted in a complete loss of connection.

This can be caused by the uninstall script not being properly executed. I see Volumio has been patched to execute uninstall-scripts, this was not implemented yet. It should in the new version, can tell which build though.

> So if I stop de server on the client device, and then reload the settings page, it looks like the server is enabled, which is confusing.

Did you save your configuration? Because 'flicking the switch' is not enough, you have to press save to commit the settings to the config.json file.

**Comment by webbes** [comment] 2017-06-26 05:55
I used the latest version of volumio, so the uninstall script should have run. I do save the configuration but this doesn't seem to persist.

**Comment by Saiyato** [comment] 2017-06-28 08:34
I found the configuration problem, will provide a fix asap! :) As for the uninstall, this works when downloading the sources from Volumio, haven't re-imaged in a while, so I'm not sure everything is in the latest image already.

**Closed as completed** 2017-06-28 08:53 UTC
Labels: bug
